spring:
  application:
    name: backend-item
server:
  port: 9011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
FTP_HOST: 192.168.163.130
FTP_PORT: 21
FTP_USERNAME: ftpuser
FTP_PASSWORD: ftpuser
FTP_BASEPATH: /home/ftpuser
#分布式事务
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070