# 服务名称
spring:
  application:
    name: common-item
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/solr_test?characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
# 服务端口
server:
  port: 9010
# 注册中心
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
#分布式事务
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070